// <auto-generated />
using System;
using CommunicaAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunicaAI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626084628_UpdateInterviewResultModel")]
    partial class UpdateInterviewResultModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunicaAI.Models.AnswerEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClarityScore")
                        .HasColumnType("integer");

                    b.Property<int>("CompletenessScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Improvements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewAnswerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnicalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewAnswerId")
                        .IsUnique();

                    b.ToTable("AnswerEvaluations");
                });

            modelBuilder.Entity("CommunicaAI.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId");

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("integer");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnicalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId")
                        .IsUnique();

                    b.ToTable("InterviewResults");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("CommunicaAI.Models.QuestionBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Role", "Category", "Difficulty");

                    b.ToTable("QuestionBanks");
                });

            modelBuilder.Entity("CommunicaAI.Models.UserMediaProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioContentType")
                        .HasColumnType("text");

                    b.Property<string>("AudioPublicId")
                        .HasColumnType("text");

                    b.Property<long?>("AudioSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AudioUploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoContentType")
                        .HasColumnType("text");

                    b.Property<string>("VideoPublicId")
                        .HasColumnType("text");

                    b.Property<long?>("VideoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VideoUploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserMediaProfile");
                });

            modelBuilder.Entity("CommunicaAI.Models.UserVerificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrollmentAudioPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnrollmentAudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnrollmentVideoPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnrollmentVideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserVerificationProfiles");
                });

            modelBuilder.Entity("InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("InterviewQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId")
                        .IsUnique();

                    b.HasIndex("InterviewSessionId");

                    b.ToTable("InterviewAnswers");
                });

            modelBuilder.Entity("CommunicaAI.Models.AnswerEvaluation", b =>
                {
                    b.HasOne("InterviewAnswer", "InterviewAnswer")
                        .WithOne("Evaluation")
                        .HasForeignKey("CommunicaAI.Models.AnswerEvaluation", "InterviewAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewAnswer");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewQuestion", b =>
                {
                    b.HasOne("CommunicaAI.Models.InterviewSession", "InterviewSession")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewResult", b =>
                {
                    b.HasOne("CommunicaAI.Models.InterviewSession", "InterviewSession")
                        .WithOne()
                        .HasForeignKey("CommunicaAI.Models.InterviewResult", "InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("CommunicaAI.Models.UserMediaProfile", b =>
                {
                    b.HasOne("CommunicaAI.Models.AppUser", "User")
                        .WithOne("MediaProfile")
                        .HasForeignKey("CommunicaAI.Models.UserMediaProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommunicaAI.Models.UserVerificationProfile", b =>
                {
                    b.HasOne("CommunicaAI.Models.AppUser", "User")
                        .WithOne("VerificationProfile")
                        .HasForeignKey("CommunicaAI.Models.UserVerificationProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewAnswer", b =>
                {
                    b.HasOne("CommunicaAI.Models.InterviewQuestion", "InterviewQuestion")
                        .WithOne("Answer")
                        .HasForeignKey("InterviewAnswer", "InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunicaAI.Models.InterviewSession", "InterviewSession")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewQuestion");

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("CommunicaAI.Models.AppUser", b =>
                {
                    b.Navigation("MediaProfile");

                    b.Navigation("VerificationProfile");
                });

            modelBuilder.Entity("CommunicaAI.Models.InterviewQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("InterviewAnswer", b =>
                {
                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
